[toolchain]
package_manager = "npm"
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aerospacer_protocol = "HQbV7SKnWuWPHEci5eejsnJG7qwYuQkGzJHJ6nhLZhxk"
aerospacer_oracle = "8Fu4YnUkfmrGQ3PTVoPfsAGjQ6NistGsiKpBEkPhzA2K"
aerospacer_fees = "FyBGDrxVAdTnwKeXFrhQR1UyyJhqbfQmZrXWqZuhYkAj"

[programs.devnet]
aerospacer_protocol = "HQbV7SKnWuWPHEci5eejsnJG7qwYuQkGzJHJ6nhLZhxk"
aerospacer_oracle = "8Fu4YnUkfmrGQ3PTVoPfsAGjQ6NistGsiKpBEkPhzA2K"
aerospacer_fees = "FyBGDrxVAdTnwKeXFrhQR1UyyJhqbfQmZrXWqZuhYkAj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=e153d2eb-e16c-4b9d-a369-c418cfff8e13"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
